### ISSUE TITLE
`empty git-upload-pack given` errors since v5.4.0

### ISSUE THREAD

**Issue by hiddeco** [go-git/go-git#328]
We are [extensive](https://github.com/fluxcd/source-controller) [consumers](https://github.com/fluxcd/image-automation-controller) [of this library](https://github.com/fluxcd/flux2) and besides the issue reported in #323, we have seen an increase of `empty git-upload-pack given` errors reported by our users since we upgraded from `v5.3.0` to `v5.4.x`.

The error seems unrelated to the Git v2 protocol as reported in #64 or #157, given users that previously were able to perform operations on their e.g. GitHub repository using `v5.3.0` are now no longer able to do so using `v5.4.x`.

~Diving into the changelog nothing directly related seems to have changed, except for some plumbing changes in #246.~

**Comment by zeripath** [comment]
I think this should be fixed following the merging of #329

**Comment by mcuadros** [comment]
Can you test this against the new v5.4.2?

**Comment by hiddeco** [comment]
Based on https://github.com/fluxcd/image-automation-controller/issues/176#issuecomment-852963792, this does not seem to have been the cause.

**Comment by Robbilie** [comment]
looking at the MR, we are facing this issue with a basically fresh repo, single branch, ~10 super simple yaml files, nothing really big in any way

**Comment by zeripath** [comment]
I think this can be closed now?

**Comment by laszlocph** [comment]
@zeripath I still get this error with v5.4.2

With the following scenario:

```
opts := &git.CloneOptions{
		URL: fmt.Sprintf("%s/%s", "https://github.com", repoName),
		Auth: &http.BasicAuth{
			Username: user,
			Password: token,
		},
		Depth: 100,
	}
repo, err := git.PlainClone(repoPath, false, opts)
```

```
err = repo.Fetch(&git.FetchOptions{
		RefSpecs: []config.RefSpec{"refs/*:refs/*", "HEAD:refs/heads/HEAD"},
		Auth: &http.BasicAuth{
			Username: user,
			Password: token,
		},
		Depth: 100,
	})
```

```
repo, err := git.PlainOpen(path)
worktree.Pull(&git.PullOptions{
		RemoteName: "origin",
		Auth: &http.BasicAuth{
			Username: user,
			Password: token,
		},
	})
```

**Comment by zeripath** [comment]
Ok then I don't think this can be related to my changes. If you have a specific and repeatable test case you could try to bisect?

**Comment by qhua948** [comment]
Same problem here, first clone went ok, same problem when doing subsequent pull/fetch

**Comment by linneawang** [comment]
> Same problem here, first clone went ok, same problem when doing subsequent pull/fetch

same here

**Comment by takirala** [comment]
> Same problem here, first clone went ok, same problem when doing subsequent pull/fetch

same here

**Comment by laszlocph** [comment]
The issue started with https://github.com/go-git/go-git/commit/320db9af8ba8b0046e833013504eb07c61a3573c

Works before
```
$ go get github.com/go-git/go-git/v5@db2bc57350561c4368a8d32c42476699b48d2a09
go get: downgraded github.com/go-git/go-git/v5 v5.3.1-0.20210512203949-320db9af8ba8 => v5.3.1-0.20210503000431-db2bc5735056
$ laszlo@laszlo-XPS-13-9370:~/projects/empty-uploadpack$ go test
PASS
ok  	github.com/laszlocph/empty-upload-pack	1.847s
```

Fails afterwards:

```
$laszlo@laszlo-XPS-13-9370:~/projects/empty-uploadpack$ go get github.com/go-git/go-git/v5@320db9af8ba8b0046e833013504eb07c61a3573c
go get: upgraded github.com/go-git/go-git/v5 v5.3.1-0.20210503000431-db2bc5735056 => v5.3.1-0.20210512203949-320db9af8ba8
$ laszlo@laszlo-XPS-13-9370:~/projects/empty-uploadpack$ go test
--- FAIL: Test_emptyUploadPack (1.50s)
    uploadpack_test.go:41: empty git-upload-pack given
FAIL
exit status 1
FAIL	github.com/laszlocph/empty-upload-pack	1.509s
```

**Comment by greenpau** [comment]
Have the same issue https://github.com/greenpau/caddy-git/issues/2 when using `PlainOpen()` followed by worktree `Pull()`.

**Comment by greenpau** [comment]
The `empty git-upload-pack given` is being returned by `remote.fetch` call in `PullContext()`.

https://github.com/go-git/go-git/blob/a5bbcd278ab1467bf9a8dfa615649b6c4d699119/worktree.go#L73-L82

The `fetch()` returns error from `fetchPack` here:

https://github.com/go-git/go-git/blob/a5bbcd278ab1467bf9a8dfa615649b6c4d699119/remote.go#L463-L465

The `fetchPack` returns error from `transport.UploadPackSession`.`UploadPack`:

https://github.com/go-git/go-git/blob/a5bbcd278ab1467bf9a8dfa615649b6c4d699119/remote.go#L547-L550

The `UploadPackSession` is an interface and it has `UploadPack` method:

https://github.com/go-git/go-git/blob/a5bbcd278ab1467bf9a8dfa615649b6c4d699119/plumbing/transport/common.go#L74-L84

The `UploadPack` returns `transport.ErrEmptyUploadPackRequest`, because the `req` in `remote.go` passes an empty request.

https://github.com/go-git/go-git/blob/a5bbcd278ab1467bf9a8dfa615649b6c4d699119/plumbing/transport/http/upload_pack.go#L35-L41

🤔 should we modify `remote.go` such that when the req is empty, then we don't do `UploadPack()`?

**Comment by ydcool** [comment]
Got same issue.  I have to downgrade to v5.3.0, what's the progress now?

**Comment by talwat** [comment]
I also have the same issue, v5.3.0 seems to work but I'm worried about using an older version. Is there any kind of workaround?

**Comment by greenpau** [comment]
@ydcool , @talwat , I am solving the issue by not specifying depth.

**Comment by talwat** [comment]
Yes, but limiting depth is super useful and I need it. If I don’t specify depth my program is way slower.

**Comment by sudowill** [comment]
> Got same issue. I have to downgrade to v5.3.0, what's the progress now?

Same here.

**Comment by mmessmore** [comment]
I wasn't specifying Depth on the Pull(), but was on the initial Clone() and get this error on any subsequent Pull().

If I remove specifying Depth on the Clone(), the Pull()s work fine.

This is not ideal for me since my service is useless until the initial clone is complete and making it shallower reduces that time.  The repo I'm working with has a very long (and mostly irrelevant) history, so I was trying to limit that initial transfer.  I just need the last couple weeks of changes at a given point in time.

**Comment by fbozic** [comment]
Same here with version `v5.5.1`, downgrade to `v5.3.0` and it works

**Comment by talwat** [comment]
This issue has remained present and active for a while now, and the best solution I found is to just use os.Exec.

**Comment by CubicrootXYZ** [comment]
This issue is still persistent with `v5.6.1`. Downgraded to `v5.3.0` which seems to work for now. Though, this is not ideal since the update path is blocked through this issue.

**Comment by talwat** [comment]
Yeah, after 2 years I'm not sure this issue is ever going to get fixed.

**Comment by Charles546** [comment]
Hey team, what is going on here? Are we not going to fix this?

**Comment by AriehSchneier** [comment]
@Charles546 Do you have a test to reproduce this? Have you tried with latest master? I have made a few fixes so that fetching shallow repos now work (but they haven't all been released yet).

If you can still reproduce it with the master branch I can take a look to see if I can get make fix in for you.

**Comment by taigrr** [comment]
These changes did end up fixing the issue I was having in one of my repos. 

Any chance we could get a new version tagged release so we can `go get -u` ?

Thanks in advance, go-git team.

**Comment by pjbgf** [comment]
@taigrr The version `v5.8.0` was released last week and should contain the fix.

**Comment by AriehSchneier** [comment]
@pjbgf I took a look and this case is different to what I fixed. This is trying to unshallow a repo after it was cloned as shallow. If you add this code to the end of `TestFetchAfterShallowClone` it reproduces the issue:
```
	// Try fetch with no depth specified to unshallow
	s.testFetch(c, r, &FetchOptions{
		Tags: NoTags,

		RefSpecs: []config.RefSpec{
			"+refs/heads/master:refs/heads/master",
			"+refs/heads/master:refs/remotes/origin/master",
		},
	}, []*plumbing.Reference{
		plumbing.NewReferenceFromStrings("refs/heads/master", sha5.String()),
		plumbing.NewReferenceFromStrings("refs/remotes/origin/master", sha5.String()),
		plumbing.NewSymbolicReference("HEAD", "refs/heads/master"),
	})
```
It seems we are only handling shallow commits if we are requesting a depth greater than 0, so it fails if we try to unshallow our clone.

In `Remote.fetch` I tried changing this section:
```
	if !req.Depth.IsZero() {
		req.Shallows, err = r.s.Shallow()
		if err != nil {
			return nil, fmt.Errorf("existing checkout is not shallow")
		}
	}
```
to
```
	req.Shallows, err = r.s.Shallow()
	if err != nil && !req.Depth.IsZero() {
		return nil, fmt.Errorf("existing checkout is not shallow")
	} else if len(req.Shallows) > 0 && req.Depth.IsZero() {
		// trying to unshallow, need to set the shallow capability
		if err := req.Capabilities.Set(capability.Shallow); err != nil {
			return nil, err
		}
	}
```

However it seems we don't update the existing list of shallows correctly (ie remove commits that are no longer shallow) during `fetchPack` and I don't know the git protocol well enough to know what is missing from the code.

Any chance you can take a look?

**Comment by pjbgf** [comment]
@AriehSchneier I will try to take a look at it later on this week. In the meantime, will re-open this issue.

**Comment by pjbgf** [comment]
@AriehSchneier I had an initial look at this, by shallow cloning the repo then unshallowing it:

`GIT_TRACE_PACKET=true git -c protocol.version=1 clone --no-progress --no-tags --depth 1 --single-branch https://github.com/go-git/go-git`

`GIT_TRACE_PACKET=true git -c protocol.version=1 fetch --no-progress --unshallow`

On the fetch (trying to unshallow), `go-git` does not seem to be sending that `shallow` and `deepen` across:
```
09:32:38.194674 pkt-line.c:86           packet:   fetch-pack> want cd6170c6f808453f58dcfd15c6c59345e3df402b multi_ack_detailed no-done side-band-64k thin-pack no-progress ofs-delta deepen-since deepen-not agent=git/2.41.0
09:32:38.194680 pkt-line.c:86           packet:   fetch-pack> shallow cd6170c6f808453f58dcfd15c6c59345e3df402b
09:32:38.194683 pkt-line.c:86           packet:   fetch-pack> deepen 2147483647
09:32:38.194685 pkt-line.c:86           packet:   fetch-pack> 0000
```

Which means it would not receive the `unshallow` back:
```
09:32:38.194741 pkt-line.c:86           packet:          git< 00a4want cd6170c6f808453f58dcfd15c6c59345e3df402b multi_ack_detailed no-done side-band-64k thin-pack no-progress ofs-delta deepen-since deepen-not agent=git/2.41.00034shallow cd6170c6f808453f58dcfd15c6c59345e3df402b0015deepen 21474836470000
09:32:38.194751 pkt-line.c:86           packet:          git< 0000
09:32:38.343729 pkt-line.c:86           packet:   fetch-pack< unshallow cd6170c6f808453f58dcfd15c6c59345e3df402b
09:32:38.343766 pkt-line.c:86           packet:   fetch-pack< 0000
```

**Comment by pjbgf** [comment]
@williambanfield Just wanted to call out on your example that you probably want to add `Tags: git.NoTags` on your `CloneOptions`, as that will impact the amount of commits you will be shallowing as it will bring depth + the number of unique referenced commits from all the tags within the repository. You can check that with `cat .git/shallow`.

**Comment by Tang8330** [comment]
Still getting this error when going a clone with a depth specified, then running `git pull` without depth

**Comment by Xe** [comment]
I just ran into this today
