### ISSUE TITLE
Error: ssh: handshake failed: knownhosts: key mismatch

### ISSUE THREAD

**Issue by jarbus** [go-git/go-git#619]
Using [git-bug](https://github.com/MichaelMure/git-bug), getting this error when I try to push to remote:
```
➜ git bug push
Error: ssh: handshake failed: knownhosts: key mismatch
```
Reported it here: https://github.com/MichaelMure/git-bug/issues/929. Dev said it might be a problem with go-git. I can push and pull with regular git, so I'm wondering if git has an ssh configuration that go-git doesn't support.

**Comment by farhaven** [comment]
See https://github.com/go-git/go-git/issues/516 for a workaround for this.

**Comment by pjbgf** [comment]
That sounds like an issue with the picked algorithm used during the SSH handshake. That should be fixed via https://github.com/go-git/go-git/issues/411.

Are you using the latest version of go-git? If you do, do may have entries in your `known_hosts` that are not aligned with the key you are providing.

**Comment by MichaelMure** [comment]
> Are you using the latest version of go-git? If you do, do may have entries in your known_hosts that are not aligned with the key you are providing.

If I'm not mistaken, that fix has not been released in a tagged version yet.

**Comment by pjbgf** [comment]
@MichaelMure you may update to the latest version from master with:
```
go get github.com/go-git/go-git/v5@master
```

**Comment by jarbus** [comment]
@pjbgf I'm still facing this issue after running this command and recompiling

**Comment by jarbus** [comment]
This issue has since been solved by adding my id_rsa key to ssh-agent, which I didn't do initially because I was using a different key with github
